import { TeamId, TeamInfo } from './types';

export const TEAMS: Record<TeamId, TeamInfo> = {
  tien_phong: {
    id: 'tien_phong',
    name: 'Khối Tiên Phong',
    shortName: 'Tiên Phong',
    icon: '⚒️',
    color: 'text-red-400',
    hexColor: '#DC2626',
    bgGradient: 'from-red-950/40 to-slate-900/80 border-red-800/40',
    borderClass: 'border-red-800/50',
    badgeBg: 'bg-red-950/50 text-red-300 border-red-800/40',
    meaning: 'Giai cấp Công nhân & Nông dân — Nền tảng gốc rễ cốt lõi của khối đại đoàn kết toàn dân tộc.',
    slogan: 'Vững gốc · Bền tâm · Quyết thắng',
    targetCount: 5,
  },
  tri_thuc: {
    id: 'tri_thuc',
    name: 'Khối Trí Thức',
    shortName: 'Trí Thức',
    icon: '💡',
    color: 'text-amber-400',
    hexColor: '#D97706',
    bgGradient: 'from-amber-950/40 to-slate-900/80 border-amber-800/40',
    borderClass: 'border-amber-800/50',
    badgeBg: 'bg-amber-950/50 text-amber-300 border-amber-800/40',
    meaning: 'Trí thức & Tinh hoa — Lực lượng kiến thiết, đổi mới sáng tạo và phát triển quốc gia.',
    slogan: 'Trí tuệ dân tộc · Khai phóng tương lai',
    targetCount: 5,
  },
  xung_kich: {
    id: 'xung_kich',
    name: 'Khối Xung Kích',
    shortName: 'Xung Kích',
    icon: '⚡',
    color: 'text-orange-400',
    hexColor: '#EA580C',
    bgGradient: 'from-orange-950/40 to-slate-900/80 border-orange-800/40',
    borderClass: 'border-orange-800/50',
    badgeBg: 'bg-orange-950/50 text-orange-300 border-orange-800/40',
    meaning: 'Thanh niên & Tuổi trẻ Việt Nam — Lực lượng rường cột kế thừa, xung kích bứt phá.',
    slogan: 'Đâu cần thanh niên có · Đâu khó có thanh niên',
    targetCount: 5,
  },
  dan_toc_ton_giao: {
    id: 'dan_toc_ton_giao',
    name: 'Khối Dân Tộc - Tôn Giáo',
    shortName: 'Dân Tộc & Tôn Giáo',
    icon: '🤝',
    color: 'text-emerald-400',
    hexColor: '#059669',
    bgGradient: 'from-emerald-950/40 to-slate-900/80 border-emerald-800/40',
    borderClass: 'border-emerald-800/50',
    badgeBg: 'bg-emerald-950/50 text-emerald-300 border-emerald-800/40',
    meaning: '54 Dân tộc anh em & Các tôn giáo — Khối hòa hợp dân tộc bền chặt, bình đẳng, tương trợ.',
    slogan: 'Muôn người một lòng · Bắc Nam một nhà',
    targetCount: 5,
  },
  kieu_bao: {
    id: 'kieu_bao',
    name: 'Khối Kiều Bào',
    shortName: 'Kiều Bào',
    icon: '✈️',
    color: 'text-purple-400',
    hexColor: '#9333EA',
    bgGradient: 'from-purple-950/40 to-slate-900/80 border-purple-800/40',
    borderClass: 'border-purple-800/50',
    badgeBg: 'bg-purple-950/50 text-purple-300 border-purple-800/40',
    meaning: 'Người Việt Nam ở nước ngoài — Bộ phận không tách rời của cộng đồng dân tộc Việt Nam.',
    slogan: 'Dù xa đất mẹ · Vẹn tấm lòng son',
    targetCount: 5,
  },
  ban_be_quoc_te: {
    id: 'ban_be_quoc_te',
    name: 'Khối Bạn Bè Quốc Tế',
    shortName: 'Bạn Bè Quốc Tế',
    icon: '🌐',
    color: 'text-sky-400',
    hexColor: '#0284C7',
    bgGradient: 'from-sky-950/40 to-slate-900/80 border-sky-800/40',
    borderClass: 'border-sky-800/50',
    badgeBg: 'bg-sky-950/50 text-sky-300 border-sky-800/40',
    meaning: 'Lực lượng yêu chuộng hòa bình thế giới — Kết hợp sức mạnh dân tộc với sức mạnh thời đại.',
    slogan: 'Độc lập tự chủ · Bạn hữu năm châu',
    targetCount: 5,
  },
};

export const TEAM_LIST = Object.values(TEAMS);

export function getTeamInfo(id: TeamId): TeamInfo {
  return TEAMS[id] || TEAMS.tien_phong;
}
